#!/usr/bin/env python
import sys, os

if len(sys.argv) == 1:
	print 'gpp: No input file'
	exit()

filename = sys.argv[1]

if filename.endswith('.cpp'):
	filename = filename[:-4]

full_name = filename + '.cpp'

os.system('g++ {0} -o {1} && ./{1}'.format(full_name, filename))
